#!/usr/bin/env node
/**
 * Regenerates src/data/cards.ts from scripts/card-catalog.mjs.
 *
 * Run with: npm run build:cards
 *
 * This is the only supported way to change the card catalog. Editing
 * src/data/cards.ts by hand works until the next time this script runs and
 * silently overwrites it.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { US_STATES, PACKS, COLOR_SWATCHES, RARE_THRESHOLD } from "./card-catalog.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = join(__dirname, "..", "src", "data", "cards.ts");

function slug(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/** Splits "Police - lights off" -> ["Police", "lights off"], or a trailing "(...)" -> its own line. */
function splitLabel(name) {
  const dashIdx = name.indexOf(" - ");
  if (dashIdx > -1) {
    return [name.slice(0, dashIdx), name.slice(dashIdx + 3)];
  }
  const parenMatch = name.match(/^(.*\S)\s(\([^()]*\))$/);
  if (parenMatch) return [parenMatch[1], parenMatch[2]];
  return [name, null];
}

function jsString(s) {
  return JSON.stringify(s);
}

function buildCard(id, name, points) {
  const [, qualifier] = splitLabel(name);
  const fields = [`id: ${jsString(id)}`, `name: ${jsString(name)}`, `points: ${points}`];
  if (points >= RARE_THRESHOLD) fields.push("rare: true");
  if (qualifier) fields.push(`qualifier: ${jsString(qualifier)}`);
  return `{ ${fields.join(", ")} }`;
}

function buildGroup(pid, group) {
  const cards = group.cards
    .map(([name, points]) => buildCard(`${pid}-${slug(name)}`, name, points))
    .join(",\n          ");
  const label = group.label === null ? "null" : jsString(group.label);
  return `      { label: ${label}, cards: [\n          ${cards},\n        ] }`;
}

function buildCategory(pack) {
  const groups = pack.groups.map((g) => buildGroup(pack.id, g)).join(",\n");
  const extras = [];
  if (pack.hidden) extras.push("hidden: true");
  if (pack.style) extras.push(`style: ${jsString(pack.style)}`);
  return (
    `  {\n` +
    `    id: ${jsString(pack.id)},\n` +
    `    label: ${jsString(pack.label)},\n` +
    (extras.length ? `    ${extras.join(",\n    ")},\n` : "") +
    `    groups: [\n${groups},\n    ],\n` +
    `  }`
  );
}

const plateCards = US_STATES.map(([abbr, full]) => {
  return `        { id: ${jsString("plate-" + abbr)}, name: ${jsString(full)}, points: 5, qualifier: ${jsString(
    "(" + abbr + ")"
  )} }`;
}).join(",\n");

let cardCount = 0;

const platesCategory =
  `  {\n` +
  `    id: "us-plates",\n` +
  `    label: "US Plates",\n` +
  `    style: "plate",\n` +
  `    groups: [\n` +
  `      { label: null, cards: [\n${plateCards},\n      ] }\n` +
  `    ],\n` +
  `  }`;

for (const pack of PACKS) {
  for (const group of pack.groups) cardCount += group.cards.length;
}
const totalCards = cardCount + US_STATES.length;

const categoriesCode = [platesCategory, ...PACKS.map(buildCategory)].join(",\n");

const header = `// AUTO-GENERATED by scripts/build-cards.mjs from scripts/card-catalog.mjs.
// Do not edit by hand — your changes will be overwritten.
// To change the catalog: edit scripts/card-catalog.mjs, then run \`npm run build:cards\`.

export type Card = {
  id: string;
  name: string;
  points: number;
  rare?: boolean;
  /** Secondary label rendered on line 2, e.g. "(AL)" or "lights off". */
  qualifier?: string;
};

export type Group = { label: string | null; cards: Card[] };

export type Category = {
  id: string;
  label: string;
  groups: Group[];
  hidden?: boolean;
  style?: "plate" | "sign" | "swatch";
};

`;

const tail = `
/** Flat lookup of every card by id — used for scoring and history replay. */
export const CARD_INDEX: Record<string, Card & { categoryId: string }> = (() => {
  const idx: Record<string, Card & { categoryId: string }> = {};
  for (const cat of CATEGORIES) {
    for (const group of cat.groups) {
      for (const card of group.cards) idx[card.id] = { ...card, categoryId: cat.id };
    }
  }
  return idx;
})();

export const VISIBLE_CATEGORIES = CATEGORIES.filter((c) => !c.hidden);

export const TOTAL_POSSIBLE = VISIBLE_CATEGORIES.reduce(
  (sum, cat) => sum + cat.groups.reduce((s, g) => s + g.cards.reduce((n, c) => n + c.points, 0), 0),
  0
);

export const TOTAL_CARDS = CATEGORIES.reduce(
  (sum, cat) => sum + cat.groups.reduce((s, g) => s + g.cards.length, 0),
  0
);

/** Splits "Police - lights off" into ["Police", "lights off"] for two-line cards. */
export function splitLabel(card: Card): [string, string | null] {
  if (!card.qualifier) return [card.name, null];
  const d = card.name.indexOf(" - ");
  if (d > -1) return [card.name.slice(0, d), card.qualifier];
  return [card.name.slice(0, card.name.length - card.qualifier.length).trim(), card.qualifier];
}
`;

const body =
  `export const CATEGORIES: Category[] = [\n${categoriesCode}\n];\n\n` +
  `export const COLOR_SWATCHES: Record<string, string> = ${JSON.stringify(COLOR_SWATCHES, null, 2)};\n`;

writeFileSync(OUT_PATH, header + body + tail, "utf8");

const catCount = PACKS.length + 1;
console.log(`✓ src/data/cards.ts regenerated — ${catCount} categories, ${totalCards} cards`);
