// AUTO-GENERATED by scripts/build-cards.mjs from scripts/card-catalog.mjs.
// Do not edit by hand — your changes will be overwritten.
// To change the catalog: edit scripts/card-catalog.mjs, then run `npm run build:cards`.

export type Card = {
  id: string;
  name: string;
  points: number;
  rare?: boolean;
  /** Secondary label rendered on line 2, e.g. "(AL)" or "lights off". */
  qualifier?: string;
};

export type Group = { label: string | null; cards: Card[] };

export type Category = {
  id: string;
  label: string;
  groups: Group[];
  hidden?: boolean;
  style?: "plate" | "sign" | "swatch";
};

export const CATEGORIES: Category[] = [
  {
    id: "us-plates",
    label: "US Plates",
    style: "plate",
    groups: [
      { label: null, cards: [
        { id: "plate-AL", name: "Alabama", points: 5, qualifier: "(AL)" },
        { id: "plate-AK", name: "Alaska", points: 5, qualifier: "(AK)" },
        { id: "plate-AZ", name: "Arizona", points: 5, qualifier: "(AZ)" },
        { id: "plate-AR", name: "Arkansas", points: 5, qualifier: "(AR)" },
        { id: "plate-CA", name: "California", points: 5, qualifier: "(CA)" },
        { id: "plate-CO", name: "Colorado", points: 5, qualifier: "(CO)" },
        { id: "plate-CT", name: "Connecticut", points: 5, qualifier: "(CT)" },
        { id: "plate-DE", name: "Delaware", points: 5, qualifier: "(DE)" },
        { id: "plate-DC", name: "Washington DC", points: 5, qualifier: "(DC)" },
        { id: "plate-FL", name: "Florida", points: 5, qualifier: "(FL)" },
        { id: "plate-GA", name: "Georgia", points: 5, qualifier: "(GA)" },
        { id: "plate-HI", name: "Hawaii", points: 5, qualifier: "(HI)" },
        { id: "plate-ID", name: "Idaho", points: 5, qualifier: "(ID)" },
        { id: "plate-IL", name: "Illinois", points: 5, qualifier: "(IL)" },
        { id: "plate-IN", name: "Indiana", points: 5, qualifier: "(IN)" },
        { id: "plate-IA", name: "Iowa", points: 5, qualifier: "(IA)" },
        { id: "plate-KS", name: "Kansas", points: 5, qualifier: "(KS)" },
        { id: "plate-KY", name: "Kentucky", points: 5, qualifier: "(KY)" },
        { id: "plate-LA", name: "Louisiana", points: 5, qualifier: "(LA)" },
        { id: "plate-ME", name: "Maine", points: 5, qualifier: "(ME)" },
        { id: "plate-MD", name: "Maryland", points: 5, qualifier: "(MD)" },
        { id: "plate-MA", name: "Massachusetts", points: 5, qualifier: "(MA)" },
        { id: "plate-MI", name: "Michigan", points: 5, qualifier: "(MI)" },
        { id: "plate-MN", name: "Minnesota", points: 5, qualifier: "(MN)" },
        { id: "plate-MS", name: "Mississippi", points: 5, qualifier: "(MS)" },
        { id: "plate-MO", name: "Missouri", points: 5, qualifier: "(MO)" },
        { id: "plate-MT", name: "Montana", points: 5, qualifier: "(MT)" },
        { id: "plate-NE", name: "Nebraska", points: 5, qualifier: "(NE)" },
        { id: "plate-NV", name: "Nevada", points: 5, qualifier: "(NV)" },
        { id: "plate-NH", name: "New Hampshire", points: 5, qualifier: "(NH)" },
        { id: "plate-NJ", name: "New Jersey", points: 5, qualifier: "(NJ)" },
        { id: "plate-NM", name: "New Mexico", points: 5, qualifier: "(NM)" },
        { id: "plate-NY", name: "New York", points: 5, qualifier: "(NY)" },
        { id: "plate-NC", name: "North Carolina", points: 5, qualifier: "(NC)" },
        { id: "plate-ND", name: "North Dakota", points: 5, qualifier: "(ND)" },
        { id: "plate-OH", name: "Ohio", points: 5, qualifier: "(OH)" },
        { id: "plate-OK", name: "Oklahoma", points: 5, qualifier: "(OK)" },
        { id: "plate-OR", name: "Oregon", points: 5, qualifier: "(OR)" },
        { id: "plate-PA", name: "Pennsylvania", points: 5, qualifier: "(PA)" },
        { id: "plate-RI", name: "Rhode Island", points: 5, qualifier: "(RI)" },
        { id: "plate-SC", name: "South Carolina", points: 5, qualifier: "(SC)" },
        { id: "plate-SD", name: "South Dakota", points: 5, qualifier: "(SD)" },
        { id: "plate-TN", name: "Tennessee", points: 5, qualifier: "(TN)" },
        { id: "plate-TX", name: "Texas", points: 5, qualifier: "(TX)" },
        { id: "plate-UT", name: "Utah", points: 5, qualifier: "(UT)" },
        { id: "plate-VT", name: "Vermont", points: 5, qualifier: "(VT)" },
        { id: "plate-VA", name: "Virginia", points: 5, qualifier: "(VA)" },
        { id: "plate-WA", name: "Washington", points: 5, qualifier: "(WA)" },
        { id: "plate-WV", name: "West Virginia", points: 5, qualifier: "(WV)" },
        { id: "plate-WI", name: "Wisconsin", points: 5, qualifier: "(WI)" },
        { id: "plate-WY", name: "Wyoming", points: 5, qualifier: "(WY)" },
      ] }
    ],
  },
  {
    id: "intl-plates",
    label: "Other Plates",
    groups: [
      { label: "Canada", cards: [
          { id: "intl-plates-ontario", name: "Ontario", points: 10 },
          { id: "intl-plates-quebec", name: "Quebec", points: 10 },
          { id: "intl-plates-british-columbia", name: "British Columbia", points: 10 },
          { id: "intl-plates-alberta", name: "Alberta", points: 10 },
          { id: "intl-plates-manitoba", name: "Manitoba", points: 10 },
          { id: "intl-plates-saskatchewan", name: "Saskatchewan", points: 10 },
          { id: "intl-plates-nova-scotia", name: "Nova Scotia", points: 10 },
          { id: "intl-plates-new-brunswick", name: "New Brunswick", points: 10 },
          { id: "intl-plates-newfoundland-and-labrador", name: "Newfoundland and Labrador", points: 10 },
          { id: "intl-plates-prince-edward-island", name: "Prince Edward Island", points: 10 },
          { id: "intl-plates-yukon", name: "Yukon", points: 10 },
          { id: "intl-plates-northwest-territories", name: "Northwest Territories", points: 10 },
          { id: "intl-plates-nunavut", name: "Nunavut", points: 10 },
        ] },
      { label: "Mexico & Territories", cards: [
          { id: "intl-plates-mexico-any-state", name: "Mexico - any state", points: 15, qualifier: "any state" },
          { id: "intl-plates-puerto-rico", name: "Puerto Rico", points: 25 },
          { id: "intl-plates-us-virgin-islands", name: "US Virgin Islands", points: 50, rare: true },
        ] },
    ],
  },
  {
    id: "responders",
    label: "Emergency",
    groups: [
      { label: "Police", cards: [
          { id: "responders-police-lights-off", name: "Police - lights off", points: 5, qualifier: "lights off" },
          { id: "responders-police-lights-siren", name: "Police - lights & siren", points: 10, qualifier: "lights & siren" },
          { id: "responders-police-car-pulled-over", name: "Police - car pulled over", points: 10, qualifier: "car pulled over" },
        ] },
      { label: "Ambulance", cards: [
          { id: "responders-ambulance-lights-off", name: "Ambulance - lights off", points: 5, qualifier: "lights off" },
          { id: "responders-ambulance-lights-siren", name: "Ambulance - lights & siren", points: 10, qualifier: "lights & siren" },
        ] },
      { label: "Fire", cards: [
          { id: "responders-fire-truck-lights-off", name: "Fire truck - lights off", points: 5, qualifier: "lights off" },
          { id: "responders-fire-truck-lights-siren", name: "Fire truck - lights & siren", points: 10, qualifier: "lights & siren" },
        ] },
    ],
  },
  {
    id: "vehicles",
    label: "Vehicles",
    groups: [
      { label: "Cars & Motorcycles", cards: [
          { id: "vehicles-motorcycle-standard", name: "Motorcycle - standard", points: 5, qualifier: "standard" },
          { id: "vehicles-motorcycle-3-wheeled", name: "Motorcycle - 3-wheeled", points: 10, qualifier: "3-wheeled" },
          { id: "vehicles-motorcycle-with-sidecar", name: "Motorcycle - with sidecar", points: 25, qualifier: "with sidecar" },
          { id: "vehicles-dirt-bike", name: "Dirt bike", points: 5 },
          { id: "vehicles-atv", name: "ATV", points: 10 },
          { id: "vehicles-convertible-top-down", name: "Convertible - top down", points: 10, qualifier: "top down" },
          { id: "vehicles-jeep-top-down", name: "Jeep - top down", points: 10, qualifier: "top down" },
          { id: "vehicles-jeep-doors-off", name: "Jeep - doors off", points: 25, qualifier: "doors off" },
          { id: "vehicles-classic-vw-beetle", name: "Classic VW Beetle", points: 15 },
          { id: "vehicles-classic-vw-microbus", name: "Classic VW Microbus", points: 15 },
          { id: "vehicles-barcycle-party-bike", name: "Barcycle/party bike", points: 15 },
        ] },
      { label: "Trucks & Vans", cards: [
          { id: "vehicles-delivery-van", name: "Delivery van", points: 5 },
          { id: "vehicles-mail-truck", name: "Mail truck", points: 5 },
          { id: "vehicles-garbage-truck", name: "Garbage truck", points: 5 },
          { id: "vehicles-dump-truck", name: "Dump truck", points: 5 },
          { id: "vehicles-cement-mixer", name: "Cement mixer", points: 5 },
          { id: "vehicles-tanker-oil-truck", name: "Tanker/oil truck", points: 5 },
          { id: "vehicles-tow-truck", name: "Tow truck", points: 5 },
          { id: "vehicles-car-carrying-truck", name: "Car carrying truck", points: 5 },
          { id: "vehicles-construction-vehicle", name: "Construction vehicle", points: 5 },
          { id: "vehicles-log-truck", name: "Log truck", points: 10 },
          { id: "vehicles-tandem-truck", name: "Tandem truck", points: 10 },
          { id: "vehicles-semi-with-trailer", name: "Semi - with trailer", points: 5, qualifier: "with trailer" },
          { id: "vehicles-semi-without-trailer", name: "Semi - without trailer", points: 15, qualifier: "without trailer" },
          { id: "vehicles-food-truck", name: "Food truck", points: 10 },
          { id: "vehicles-ice-cream-truck", name: "Ice cream truck", points: 15 },
          { id: "vehicles-armored-truck", name: "Armored truck", points: 15 },
          { id: "vehicles-military-vehicle", name: "Military vehicle", points: 15 },
        ] },
      { label: "Buses", cards: [
          { id: "vehicles-school-bus", name: "School bus", points: 5 },
          { id: "vehicles-city-bus", name: "City bus", points: 5 },
          { id: "vehicles-shuttle-bus", name: "Shuttle bus", points: 5 },
          { id: "vehicles-coach-charter-bus", name: "Coach/charter bus", points: 5 },
        ] },
      { label: "Towing & Trailers", cards: [
          { id: "vehicles-boat-on-trailer", name: "Boat on trailer", points: 5 },
          { id: "vehicles-jet-ski-on-trailer", name: "Jet ski on trailer", points: 5 },
          { id: "vehicles-boat-trailer-no-boat", name: "Boat trailer - no boat", points: 15, qualifier: "no boat" },
          { id: "vehicles-camper-trailer", name: "Camper trailer", points: 5 },
          { id: "vehicles-airstream-trailer", name: "Airstream trailer", points: 10 },
          { id: "vehicles-rv-motorhome", name: "RV/motorhome", points: 5 },
          { id: "vehicles-horse-trailer", name: "Horse trailer", points: 10 },
          { id: "vehicles-modular-home-being-towed", name: "Modular home being towed", points: 20 },
          { id: "vehicles-oversize-wide-load", name: "Oversize/wide load", points: 15 },
        ] },
      { label: "Gear & Racks", cards: [
          { id: "vehicles-bike-rack-loaded", name: "Bike rack - loaded", points: 5, qualifier: "loaded" },
          { id: "vehicles-bike-rack-empty", name: "Bike rack - empty", points: 5, qualifier: "empty" },
          { id: "vehicles-roof-cargo-box", name: "Roof cargo box", points: 5 },
          { id: "vehicles-kayak", name: "Kayak", points: 5 },
          { id: "vehicles-canoe", name: "Canoe", points: 5 },
          { id: "vehicles-mattress-on-roof", name: "Mattress on roof", points: 10 },
        ] },
      { label: "Air, Rail & Water", cards: [
          { id: "vehicles-plane", name: "Plane", points: 5 },
          { id: "vehicles-plane-banner-in-tow", name: "Plane - banner in tow", points: 15, qualifier: "banner in tow" },
          { id: "vehicles-helicopter", name: "Helicopter", points: 15 },
          { id: "vehicles-train", name: "Train", points: 5 },
          { id: "vehicles-barge", name: "Barge", points: 10 },
        ] },
      { label: "Quirks & Damage", cards: [
          { id: "vehicles-car-on-side-of-highway", name: "Car on side of highway", points: 10 },
          { id: "vehicles-car-missing-spare-tire", name: "Car missing spare tire", points: 20 },
          { id: "vehicles-car-driving-on-spare-tire", name: "Car driving on spare tire", points: 15 },
          { id: "vehicles-missing-headlight", name: "Missing headlight", points: 5 },
          { id: "vehicles-missing-taillight", name: "Missing taillight", points: 5 },
          { id: "vehicles-mismatched-door-color", name: "Mismatched door color", points: 15 },
          { id: "vehicles-mismatched-hood-color", name: "Mismatched hood color", points: 15 },
          { id: "vehicles-trunk-tied-down", name: "Trunk tied down", points: 15 },
          { id: "vehicles-gas-tank-door-open", name: "Gas tank door open", points: 15 },
        ] },
      { label: "Custom & Cosmetic", cards: [
          { id: "vehicles-racing-stripe", name: "Racing stripe", points: 15 },
          { id: "vehicles-flames-paint", name: "Flames (paint)", points: 15, qualifier: "(paint)" },
          { id: "vehicles-ground-effects-neon-lighting", name: "Ground effects/neon lighting", points: 15 },
          { id: "vehicles-temporary-license-plate", name: "Temporary license plate", points: 5 },
          { id: "vehicles-sports-themed-license-plate", name: "Sports-themed license plate", points: 5 },
        ] },
    ],
  },
  {
    id: "car-colors",
    label: "Car Colors",
    style: "swatch",
    groups: [
      { label: "Common", cards: [
          { id: "car-colors-white", name: "White", points: 1 },
          { id: "car-colors-black", name: "Black", points: 1 },
          { id: "car-colors-gray-silver", name: "Gray/Silver", points: 1 },
          { id: "car-colors-blue", name: "Blue", points: 1 },
          { id: "car-colors-red", name: "Red", points: 1 },
          { id: "car-colors-green", name: "Green", points: 1 },
          { id: "car-colors-brown-tan", name: "Brown/Tan", points: 1 },
          { id: "car-colors-yellow", name: "Yellow", points: 1 },
        ] },
      { label: "Rare", cards: [
          { id: "car-colors-orange", name: "Orange", points: 5 },
          { id: "car-colors-purple", name: "Purple", points: 5 },
          { id: "car-colors-gold", name: "Gold", points: 5 },
          { id: "car-colors-turquoise-teal", name: "Turquoise/Teal", points: 5 },
          { id: "car-colors-fuchsia-pink", name: "Fuchsia/Pink", points: 5 },
          { id: "car-colors-lime-bright-green", name: "Lime/Bright green", points: 5 },
          { id: "car-colors-multi-color", name: "Multi-color", points: 10 },
        ] },
    ],
  },
  {
    id: "rare",
    label: "Rare Vehicles",
    groups: [
      { label: "Exotic & Luxury", cards: [
          { id: "rare-ferrari", name: "Ferrari", points: 25 },
          { id: "rare-lamborghini", name: "Lamborghini", points: 25 },
          { id: "rare-bentley", name: "Bentley", points: 25 },
          { id: "rare-rolls-royce", name: "Rolls-Royce", points: 25 },
          { id: "rare-aston-martin", name: "Aston Martin", points: 25 },
          { id: "rare-mclaren", name: "McLaren", points: 50, rare: true },
        ] },
      { label: "Unusual & Novelty", cards: [
          { id: "rare-limo", name: "Limo", points: 15 },
          { id: "rare-golf-cart", name: "Golf cart", points: 15 },
          { id: "rare-hearse", name: "Hearse", points: 25 },
          { id: "rare-slingshot", name: "Slingshot", points: 25 },
          { id: "rare-cybertruck", name: "Cybertruck", points: 25 },
          { id: "rare-monster-truck", name: "Monster truck", points: 50, rare: true },
          { id: "rare-amish-horse-buggy", name: "Amish horse & buggy", points: 50, rare: true },
          { id: "rare-delorean", name: "DeLorean", points: 100, rare: true },
        ] },
    ],
  },
  {
    id: "other-cars",
    label: "Other Cars",
    groups: [
      { label: "Bumper Stickers & Decals", cards: [
          { id: "other-cars-family-stick-figure", name: "Family stick-figure", points: 5 },
          { id: "other-cars-sports-team", name: "Sports team", points: 5 },
          { id: "other-cars-baby-on-board", name: "Baby on board", points: 5 },
          { id: "other-cars-college-university", name: "College/university", points: 5 },
          { id: "other-cars-political", name: "Political", points: 5 },
          { id: "other-cars-pet-paw-print", name: "Pet paw print", points: 5 },
          { id: "other-cars-state-pride-ex-i-3-ny", name: "State pride (ex. I <3 NY)", points: 5, qualifier: "(ex. I <3 NY)" },
          { id: "other-cars-military-veteran", name: "Military/veteran", points: 5 },
          { id: "other-cars-religious-symbol", name: "Religious symbol", points: 5 },
          { id: "other-cars-disney", name: "Disney", points: 5 },
          { id: "other-cars-band-music", name: "Band/music", points: 5 },
          { id: "other-cars-coexist", name: "'Coexist'", points: 5 },
          { id: "other-cars-marathon-13-1-26-2", name: "Marathon (13.1 / 26.2)", points: 5, qualifier: "(13.1 / 26.2)" },
          { id: "other-cars-makes-you-laugh", name: "Makes you laugh", points: 5 },
          { id: "other-cars-makes-you-upset", name: "Makes you upset", points: 5 },
          { id: "other-cars-honk-if", name: "'Honk if...'", points: 5 },
          { id: "other-cars-i-brake-for", name: "'I brake for...'", points: 5 },
          { id: "other-cars-my-other-car-is", name: "'My other car is...'", points: 5 },
          { id: "other-cars-got", name: "'Got ___?'", points: 5 },
        ] },
      { label: "Dashboard & Mirror", cards: [
          { id: "other-cars-fuzzy-dice", name: "Fuzzy dice", points: 5 },
          { id: "other-cars-rubber-ducky", name: "Rubber ducky", points: 5 },
          { id: "other-cars-waving-cat", name: "Waving cat", points: 5 },
          { id: "other-cars-rosary-beads", name: "Rosary beads", points: 5 },
          { id: "other-cars-flower", name: "Flower", points: 5 },
          { id: "other-cars-hawaiian-lei", name: "Hawaiian lei", points: 5 },
        ] },
      { label: "Windows & Glass", cards: [
          { id: "other-cars-sun-shield-in-car", name: "Sun shield in car", points: 5 },
          { id: "other-cars-marker-window-writing", name: "Marker window writing", points: 5 },
        ] },
      { label: "People & Gestures", cards: [
          { id: "other-cars-stranger-waves-back", name: "Stranger waves back", points: 15 },
          { id: "other-cars-truck-driver-honks-back", name: "Truck driver honks back", points: 10 },
          { id: "other-cars-someone-sleeping-in-another-car", name: "Someone sleeping in another car", points: 5 },
          { id: "other-cars-feet-on-the-dash", name: "Feet on the dash", points: 5 },
          { id: "other-cars-car-blasting-music", name: "Car blasting music", points: 5 },
          { id: "other-cars-dog-with-head-out-window", name: "Dog with head out window", points: 5 },
        ] },
    ],
  },
  {
    id: "wildlife",
    label: "Wildlife",
    groups: [
      { label: "Farm & Domestic", cards: [
          { id: "wildlife-cow", name: "Cow", points: 5 },
          { id: "wildlife-horse", name: "Horse", points: 5 },
          { id: "wildlife-goat", name: "Goat", points: 5 },
          { id: "wildlife-sheep", name: "Sheep", points: 5 },
          { id: "wildlife-cat", name: "Cat", points: 5 },
        ] },
      { label: "Common", cards: [
          { id: "wildlife-squirrel", name: "Squirrel", points: 5 },
          { id: "wildlife-rabbit", name: "Rabbit", points: 5 },
          { id: "wildlife-raccoon", name: "Raccoon", points: 10 },
          { id: "wildlife-possum", name: "Possum", points: 10 },
          { id: "wildlife-deer", name: "Deer", points: 10 },
          { id: "wildlife-wild-turkey", name: "Wild turkey", points: 10 },
        ] },
      { label: "Birds", cards: [
          { id: "wildlife-seagull", name: "Seagull", points: 5 },
          { id: "wildlife-pigeon", name: "Pigeon", points: 5 },
          { id: "wildlife-hawk-eagle", name: "Hawk/eagle", points: 10 },
        ] },
      { label: "Rare", cards: [
          { id: "wildlife-llama-alpaca", name: "Llama/alpaca", points: 15 },
          { id: "wildlife-fox", name: "Fox", points: 15 },
          { id: "wildlife-elk", name: "Elk", points: 20 },
          { id: "wildlife-moose", name: "Moose", points: 25 },
          { id: "wildlife-bear", name: "Bear", points: 30 },
        ] },
    ],
  },
  {
    id: "water",
    label: "Water",
    groups: [
      { label: null, cards: [
          { id: "water-lake", name: "Lake", points: 5 },
          { id: "water-pond", name: "Pond", points: 5 },
          { id: "water-river", name: "River", points: 5 },
          { id: "water-stream-creek", name: "Stream/creek", points: 5 },
          { id: "water-reservoir", name: "Reservoir", points: 5 },
          { id: "water-marsh-swamp", name: "Marsh/swamp", points: 5 },
          { id: "water-canal", name: "Canal", points: 5 },
          { id: "water-ocean", name: "Ocean", points: 5 },
        ] },
    ],
  },
  {
    id: "places",
    label: "Places",
    groups: [
      { label: "Farm & Rural", cards: [
          { id: "places-barn", name: "Barn", points: 5 },
          { id: "places-silo", name: "Silo", points: 5 },
          { id: "places-cornfield", name: "Cornfield", points: 5 },
          { id: "places-farm-stand", name: "Farm stand", points: 10 },
          { id: "places-grain-elevator", name: "Grain elevator", points: 5 },
          { id: "places-vineyard", name: "Vineyard", points: 5 },
          { id: "places-orchard", name: "Orchard", points: 5 },
          { id: "places-windmill-turbine", name: "Windmill/turbine", points: 5 },
        ] },
      { label: "Road Infrastructure", cards: [
          { id: "places-bridge", name: "Bridge", points: 5 },
          { id: "places-covered-bridge", name: "Covered bridge", points: 15 },
          { id: "places-tunnel", name: "Tunnel", points: 5 },
          { id: "places-toll-booth", name: "Toll booth", points: 5 },
          { id: "places-state-welcome-sign", name: "State welcome sign", points: 5 },
          { id: "places-water-tower", name: "Water tower", points: 5 },
          { id: "places-drawbridge-closed", name: "Drawbridge - closed", points: 10, qualifier: "closed" },
          { id: "places-drawbridge-open", name: "Drawbridge - open", points: 15, qualifier: "open" },
        ] },
      { label: "Scenic & Historic", cards: [
          { id: "places-scenic-overlook", name: "Scenic overlook", points: 5 },
          { id: "places-historical-marker-or-sign", name: "Historical marker or sign", points: 5 },
          { id: "places-waterfall", name: "Waterfall", points: 15 },
          { id: "places-lighthouse", name: "Lighthouse", points: 15 },
          { id: "places-ferry", name: "Ferry", points: 15 },
          { id: "places-drive-in-movie-theater", name: "Drive-in movie theater", points: 25 },
        ] },
      { label: "Schools & Community", cards: [
          { id: "places-elementary-school", name: "Elementary school", points: 5 },
          { id: "places-middle-school", name: "Middle school", points: 5 },
          { id: "places-high-school", name: "High school", points: 5 },
          { id: "places-college-university", name: "College/university", points: 15 },
          { id: "places-daycare", name: "Daycare", points: 5 },
          { id: "places-public-park", name: "Public park", points: 5 },
          { id: "places-community-garden", name: "Community garden", points: 10 },
          { id: "places-playground", name: "Playground", points: 5 },
          { id: "places-cemetery", name: "Cemetery", points: 5 },
        ] },
      { label: "Sports & Recreation", cards: [
          { id: "places-sports-stadium-arena", name: "Sports stadium/arena", points: 10 },
          { id: "places-baseball-field", name: "Baseball field", points: 5 },
          { id: "places-football-field", name: "Football field", points: 5 },
          { id: "places-soccer-field", name: "Soccer field", points: 5 },
          { id: "places-basketball-court", name: "Basketball court", points: 5 },
          { id: "places-tennis-pickleball-court", name: "Tennis/pickleball court", points: 5 },
          { id: "places-golf-course", name: "Golf course", points: 5 },
          { id: "places-mini-golf-course", name: "Mini golf course", points: 10 },
          { id: "places-driving-range", name: "Driving range", points: 5 },
          { id: "places-campground", name: "Campground", points: 10 },
          { id: "places-state-park", name: "State park", points: 10 },
          { id: "places-national-park", name: "National park", points: 25 },
        ] },
      { label: "Attractions & Entertainment", cards: [
          { id: "places-amusement-park", name: "Amusement park", points: 15 },
          { id: "places-water-park", name: "Water park", points: 15 },
          { id: "places-aquarium", name: "Aquarium", points: 10 },
          { id: "places-museum", name: "Museum", points: 10 },
          { id: "places-zoo", name: "Zoo", points: 10 },
          { id: "places-casino", name: "Casino", points: 5 },
          { id: "places-town-carnival-or-fair", name: "Town carnival or fair", points: 10 },
        ] },
      { label: "Everyday Stops", cards: [
          { id: "places-gas-station", name: "Gas station", points: 5 },
          { id: "places-rest-stop", name: "Rest stop", points: 5 },
          { id: "places-mall", name: "Mall", points: 5 },
          { id: "places-car-dealership", name: "Car dealership", points: 5 },
          { id: "places-storage-facility", name: "Storage facility", points: 5 },
          { id: "places-brewery", name: "Brewery", points: 5 },
          { id: "places-porta-potty", name: "Porta potty", points: 5 },
          { id: "places-park-and-ride", name: "Park and ride", points: 5 },
          { id: "places-weigh-station", name: "Weigh station", points: 5 },
        ] },
      { label: "Transit & Civic", cards: [
          { id: "places-train-station", name: "Train station", points: 5 },
          { id: "places-bus-station", name: "Bus station", points: 5 },
          { id: "places-police-station", name: "Police station", points: 5 },
          { id: "places-fire-station", name: "Fire station", points: 5 },
        ] },
      { label: "Structures & Roads", cards: [
          { id: "places-abandoned-building", name: "Abandoned building", points: 5 },
          { id: "places-house-for-sale", name: "House for sale", points: 5 },
          { id: "places-political-lawn-sign", name: "Political lawn sign", points: 5 },
          { id: "places-smoke-stacks", name: "Smoke stacks", points: 5 },
          { id: "places-pool-above-ground", name: "Pool - above ground", points: 5, qualifier: "above ground" },
          { id: "places-pool-in-ground", name: "Pool - in-ground", points: 5, qualifier: "in-ground" },
          { id: "places-dirt-road", name: "Dirt road", points: 10 },
          { id: "places-cobblestone-road", name: "Cobblestone road", points: 10 },
        ] },
    ],
  },
  {
    id: "signs",
    label: "Signs",
    groups: [
      { label: "Exits & Markers", cards: [
          { id: "signs-1-digit-exit-sign", name: "1-digit exit sign", points: 5 },
          { id: "signs-2-digit-exit-sign", name: "2-digit exit sign", points: 5 },
          { id: "signs-3-digit-exit-sign", name: "3-digit exit sign", points: 5 },
          { id: "signs-exit-67", name: "Exit 67", points: 5 },
          { id: "signs-mile-marker-123", name: "Mile marker 123", points: 10 },
          { id: "signs-someone-s-birthday-exit-number", name: "Someone's birthday exit number", points: 15 },
        ] },
      { label: "Interstates", cards: [
          { id: "signs-even-interstate-number", name: "Even interstate number", points: 5 },
          { id: "signs-odd-interstate-number", name: "Odd interstate number", points: 5 },
        ] },
      { label: "Road Features", cards: [
          { id: "signs-grooved-road", name: "Grooved road", points: 10 },
          { id: "signs-hill-grade-warning-sign", name: "Hill grade warning sign", points: 15 },
          { id: "signs-construction-zone", name: "Construction zone", points: 5 },
          { id: "signs-train-tracks", name: "Train tracks", points: 5 },
          { id: "signs-drive-through-a-state-capital", name: "Drive through a state capital", points: 25 },
        ] },
      { label: "Word Play", cards: [
          { id: "signs-real-word-spelled-out-on-a-plate", name: "Real word spelled out on a plate", points: 10 },
          { id: "signs-unnecessary-apostrophe-on-a-sign", name: "Unnecessary apostrophe on a sign", points: 5 },
          { id: "signs-same-name-as-someone-in-the-car", name: "Same name as someone in the car", points: 5 },
        ] },
    ],
  },
  {
    id: "town-names",
    label: "Town Names",
    groups: [
      { label: "Directions", cards: [
          { id: "town-names-north", name: "North", points: 5 },
          { id: "town-names-south", name: "South", points: 5 },
          { id: "town-names-east", name: "East", points: 5 },
          { id: "town-names-west", name: "West", points: 5 },
        ] },
      { label: "Descriptors", cards: [
          { id: "town-names-old", name: "Old", points: 5 },
          { id: "town-names-new", name: "New", points: 5 },
          { id: "town-names-point", name: "Point", points: 5 },
        ] },
      { label: "Endings", cards: [
          { id: "town-names-ville", name: "-ville", points: 5 },
          { id: "town-names-boro-borough", name: "-boro/-borough", points: 5 },
          { id: "town-names-town-ton-towne", name: "-town/-ton/-towne", points: 5 },
          { id: "town-names-bury-berry", name: "-bury/-berry", points: 5 },
          { id: "town-names-field", name: "-field", points: 5 },
          { id: "town-names-bridge", name: "-bridge", points: 5 },
          { id: "town-names-valley", name: "-valley", points: 5 },
          { id: "town-names-falls", name: "-falls", points: 5 },
          { id: "town-names-lane", name: "-lane", points: 5 },
        ] },
      { label: "Wildcard", cards: [
          { id: "town-names-same-town-name-in-a-different-state", name: "Same town name in a different state", points: 5 },
        ] },
    ],
  },
  {
    id: "street-types",
    label: "Street Types",
    groups: [
      { label: "Very Common", cards: [
          { id: "street-types-street", name: "Street", points: 5 },
          { id: "street-types-road", name: "Road", points: 5 },
          { id: "street-types-drive", name: "Drive", points: 5 },
          { id: "street-types-avenue", name: "Avenue", points: 5 },
          { id: "street-types-lane", name: "Lane", points: 5 },
          { id: "street-types-court", name: "Court", points: 5 },
          { id: "street-types-boulevard", name: "Boulevard", points: 5 },
          { id: "street-types-way", name: "Way", points: 5 },
          { id: "street-types-place", name: "Place", points: 5 },
          { id: "street-types-circle", name: "Circle", points: 5 },
        ] },
      { label: "Common", cards: [
          { id: "street-types-terrace", name: "Terrace", points: 10 },
          { id: "street-types-trail", name: "Trail", points: 10 },
          { id: "street-types-highway", name: "Highway", points: 10 },
          { id: "street-types-parkway", name: "Parkway", points: 10 },
          { id: "street-types-loop", name: "Loop", points: 10 },
          { id: "street-types-square", name: "Square", points: 10 },
          { id: "street-types-crossing", name: "Crossing", points: 10 },
          { id: "street-types-ridge", name: "Ridge", points: 10 },
          { id: "street-types-run", name: "Run", points: 10 },
          { id: "street-types-landing", name: "Landing", points: 10 },
          { id: "street-types-bend", name: "Bend", points: 10 },
        ] },
      { label: "Less Common", cards: [
          { id: "street-types-pike-turnpike", name: "Pike/Turnpike", points: 15 },
          { id: "street-types-expressway", name: "Expressway", points: 15 },
          { id: "street-types-freeway", name: "Freeway", points: 15 },
          { id: "street-types-alley", name: "Alley", points: 15 },
          { id: "street-types-crescent", name: "Crescent", points: 15 },
          { id: "street-types-walk", name: "Walk", points: 15 },
          { id: "street-types-point-pointe", name: "Point/Pointe", points: 15 },
          { id: "street-types-grove", name: "Grove", points: 15 },
          { id: "street-types-glen", name: "Glen", points: 15 },
          { id: "street-types-hollow", name: "Hollow", points: 15 },
          { id: "street-types-pass", name: "Pass", points: 15 },
          { id: "street-types-row", name: "Row", points: 15 },
          { id: "street-types-cove", name: "Cove", points: 15 },
          { id: "street-types-extension", name: "Extension", points: 15 },
          { id: "street-types-plaza", name: "Plaza", points: 15 },
        ] },
    ],
  },
  {
    id: "speed-limits",
    label: "Speed Limits",
    style: "sign",
    groups: [
      { label: null, cards: [
          { id: "speed-limits-5", name: "5", points: 5 },
          { id: "speed-limits-10", name: "10", points: 5 },
          { id: "speed-limits-15", name: "15", points: 5 },
          { id: "speed-limits-20", name: "20", points: 5 },
          { id: "speed-limits-25", name: "25", points: 5 },
          { id: "speed-limits-30", name: "30", points: 5 },
          { id: "speed-limits-35", name: "35", points: 5 },
          { id: "speed-limits-40", name: "40", points: 5 },
          { id: "speed-limits-45", name: "45", points: 5 },
          { id: "speed-limits-50", name: "50", points: 5 },
          { id: "speed-limits-55", name: "55", points: 5 },
          { id: "speed-limits-60", name: "60", points: 5 },
          { id: "speed-limits-65", name: "65", points: 5 },
          { id: "speed-limits-70", name: "70", points: 5 },
          { id: "speed-limits-75", name: "75", points: 10 },
          { id: "speed-limits-80", name: "80", points: 10 },
        ] },
    ],
  },
  {
    id: "oddities",
    label: "Oddities",
    groups: [
      { label: null, cards: [
          { id: "oddities-trash-on-the-side-of-the-road", name: "Trash on the side of the road", points: 5 },
          { id: "oddities-furniture-on-the-side-of-the-road", name: "Furniture on the side of the road", points: 5 },
          { id: "oddities-tire-on-the-side-of-the-road", name: "Tire on the side of the road", points: 5 },
          { id: "oddities-tire-skid-marks", name: "Tire skid marks", points: 5 },
          { id: "oddities-graffiti", name: "Graffiti", points: 5 },
          { id: "oddities-homemade-sign-on-a-bridge", name: "Homemade sign on a bridge", points: 5 },
          { id: "oddities-roadside-cross", name: "Roadside cross", points: 5 },
        ] },
    ],
  },
  {
    id: "interactive",
    label: "Sounds",
    groups: [
      { label: null, cards: [
          { id: "interactive-car-beeping", name: "Car beeping", points: 5 },
          { id: "interactive-truck-air-brakes", name: "Truck air brakes", points: 5 },
          { id: "interactive-train-horn", name: "Train horn", points: 5 },
          { id: "interactive-church-bells", name: "Church bells", points: 5 },
          { id: "interactive-rumble-strips", name: "Rumble strips", points: 5 },
          { id: "interactive-loud-motorcycle-pipes", name: "Loud motorcycle pipes", points: 5 },
        ] },
    ],
  },
  {
    id: "family",
    label: "Family",
    groups: [
      { label: "The Classics", cards: [
          { id: "family-are-we-there-yet", name: "'Are we there yet?'", points: 5 },
          { id: "family-i-m-hungry", name: "'I'm hungry'", points: 5 },
          { id: "family-can-we-have-a-snack", name: "'Can we have a snack?'", points: 5 },
          { id: "family-i-have-to-pee", name: "'I have to pee'", points: 5 },
          { id: "family-i-m-tired", name: "'I'm tired'", points: 5 },
          { id: "family-i-m-bored", name: "'I'm bored'", points: 5 },
          { id: "family-what-can-i-do", name: "'What can I do?'", points: 5 },
        ] },
      { label: "Sounds & Smells", cards: [
          { id: "family-fart-loud", name: "Fart - loud", points: 5, qualifier: "loud" },
          { id: "family-fart-stinky", name: "Fart - stinky", points: 5, qualifier: "stinky" },
          { id: "family-burp", name: "Burp", points: 5 },
          { id: "family-sneeze", name: "Sneeze", points: 5 },
          { id: "family-snoring-in-the-car", name: "Snoring in the car", points: 5 },
          { id: "family-cow-manure-smell", name: "Cow manure smell", points: 5 },
          { id: "family-skunk-smell", name: "Skunk smell", points: 5 },
        ] },
      { label: "Car Life", cards: [
          { id: "family-falling-asleep-in-the-car", name: "Falling asleep in the car", points: 5 },
          { id: "family-food-falls-on-the-floor", name: "Food falls on the floor", points: 5 },
          { id: "family-toy-activity-falls-on-the-floor", name: "Toy/activity falls on the floor", points: 5 },
          { id: "family-urgent-bathroom-break", name: "Urgent bathroom break", points: 5 },
        ] },
    ],
  },
  {
    id: "weather",
    label: "Weather",
    groups: [
      { label: null, cards: [
          { id: "weather-rain", name: "Rain", points: 5 },
          { id: "weather-snow", name: "Snow", points: 10 },
          { id: "weather-lightning", name: "Lightning", points: 10 },
          { id: "weather-thunder", name: "Thunder", points: 10 },
          { id: "weather-sunrise", name: "Sunrise", points: 15 },
          { id: "weather-sunset", name: "Sunset", points: 15 },
          { id: "weather-rainbow", name: "Rainbow", points: 25 },
        ] },
    ],
  },
  {
    id: "novelty",
    label: "Billboards",
    hidden: true,
    groups: [
      { label: null, cards: [
          { id: "novelty-lawyer-billboard", name: "Lawyer billboard", points: 5 },
          { id: "novelty-jesus-billboard", name: "Jesus billboard", points: 5 },
        ] },
    ],
  }
];

export const COLOR_SWATCHES: Record<string, string> = {
  "White": "#ffffff",
  "Black": "#1a1a1a",
  "Gray/Silver": "#b0b4b8",
  "Blue": "#2f5fa8",
  "Red": "#c8302e",
  "Green": "#2f7d4f",
  "Brown/Tan": "#a08356",
  "Yellow": "#f2ce39",
  "Orange": "#e8762c",
  "Purple": "#7a4b9e",
  "Gold": "#c9a227",
  "Turquoise/Teal": "#3aa8a0",
  "Fuchsia/Pink": "#d6479b",
  "Lime/Bright green": "#8dc63f",
  "Multi-color": "multi"
};

/** Flat lookup of every card by id — used for scoring and history replay. */
export const CARD_INDEX: Record<string, Card & { categoryId: string }> = (() => {
  const idx: Record<string, Card & { categoryId: string }> = {};
  for (const cat of CATEGORIES) {
    for (const group of cat.groups) {
      for (const card of group.cards) idx[card.id] = { ...card, categoryId: cat.id };
    }
  }
  return idx;
})();

export const VISIBLE_CATEGORIES = CATEGORIES.filter((c) => !c.hidden);

export const TOTAL_POSSIBLE = VISIBLE_CATEGORIES.reduce(
  (sum, cat) => sum + cat.groups.reduce((s, g) => s + g.cards.reduce((n, c) => n + c.points, 0), 0),
  0
);

export const TOTAL_CARDS = CATEGORIES.reduce(
  (sum, cat) => sum + cat.groups.reduce((s, g) => s + g.cards.length, 0),
  0
);

/** Splits "Police - lights off" into ["Police", "lights off"] for two-line cards. */
export function splitLabel(card: Card): [string, string | null] {
  if (!card.qualifier) return [card.name, null];
  const d = card.name.indexOf(" - ");
  if (d > -1) return [card.name.slice(0, d), card.qualifier];
  return [card.name.slice(0, card.name.length - card.qualifier.length).trim(), card.qualifier];
}
